# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 13 Mar 2020 11:43:56 +0000
*               @ALL          1
*               @user         8
