<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 18 Mar 2020 05:30:19 -0700
 */

$conf['title'] = 'SFWiki';
$conf['lang'] = 'cs';
$conf['tagline'] = 'experimental';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['translation']['translations'] = 'en,cs';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;

// end auto-generated content
