<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 09 Sep 2020 17:21:17 +0200
 */

$conf['title'] = 'SFWiki';
$conf['lang'] = 'cs';
$conf['tagline'] = 'experimental';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['gitbacked']['pushAfterCommit'] = 1;
$conf['plugin']['gitbacked']['repoPath'] = './data/gitrepo';
$conf['plugin']['gitbacked']['repoWorkDir'] = './data/gitrepo/wiki';
$conf['plugin']['translation']['translations'] = 'en,cs';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['datadir'] = './data/gitrepo/wiki/pages';
$conf['mediadir'] = './data/gitrepo/wiki/media';
